### ISSUE TITLE
the url of SCUOJ has changed to http://acm.scu.edu.cn/soj/

### ISSUE THREAD

**Issue by Shuenhoy** [BNUACM/bnuoj-vjudge#21]

**Comment by crccw** [comment]
Fail to open that url
Is it reachable outside SCU campus?

**Comment by Shuenhoy** [comment]
@crccw I'm not in the SCU campus and it's accessable

![image](https://cloud.githubusercontent.com/assets/2196156/9509143/ca33a752-4c8e-11e5-99ed-e535eb926a0a.png)
