### ISSUE TITLE
好像codechef的提交还是有问题？

### ISSUE THREAD

**Issue by quyunhua** [BNUACM/bnuoj-vjudge#22]
好像程序没有提交过去，查看在codechef的提交记录里面是空的！

**Comment by crccw** [comment]
Not reproductive.
But Codechef has recently update the submit form, which may cause CE, you can clone the latest code and try again.

**Comment by quyunhua** [comment]
Thank you!

**Comment by quyunhua** [comment]
www.bnuoj.com
好像程序没有提交过去，查看在codechef的提交记录里面是空的！
