### ISSUE TITLE
ubuntu14 LTS 环境下 configure 出错了。。。不知道环境缺啥？

### ISSUE THREAD

**Issue by nanamomo** [BNUACM/bnuoj-vjudge#23]
ubuntu 14 LTS 环境下编译不通过。。。求助。。

root@localhost:~/bnuoj-vjudge-master/vjudge-v2# ./configure
checking whether to enable maintainer-specific portions of Makefiles... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for pthread_create in -lpthread... yes
checking for main in -lre2... no
configure: error: re2 not found

谢谢大侠指点！

**Comment by nanamomo** [comment]
configure 文件里面貌似这段。。。。

{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for main in -lre2" >&5
$as_echo_n "checking for main in -lre2... " >&6; }
if ${ac_cv_lib_re2_main+:} false; then :
  $as_echo_n "(cached) " >&6
else
  ac_check_lib_save_LIBS=$LIBS
LIBS="-lre2  $LIBS"
cat confdefs.h - <<_ACEOF >conftest.$ac_ext
/\* end confdefs.h.  */

int
main ()
{
return main ();
  ;
  return 0;
}
_ACEOF
if ac_fn_c_try_link "$LINENO"; then :
  ac_cv_lib_re2_main=yes
else
  ac_cv_lib_re2_main=no
fi
rm -f core conftest.err conftest.$ac_objext \
    conftest$ac_exeext conftest.$ac_ext
LIBS=$ac_check_lib_save_LIBS
fi
{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_re2_main" >&5
$as_echo "$ac_cv_lib_re2_main" >&6; }
if test "x$ac_cv_lib_re2_main" = xyes; then :
  cat >>confdefs.h <<_ACEOF
#define HAVE_LIBRE2 1
_ACEOF

  LIBS="-lre2 $LIBS"

else
  as_fn_error $? "**## re2 not found**" "$LINENO" 5
fi

**Comment by quyunhua** [comment]
缺少libre2库，貌似要ubuntu15才有这个库吧，我的运行在ubuntu15.04上没有这个问题
